apiVersion: v1
kind: Service
metadata:
  name: mosquitto-headless-service
  labels:
    app: mosquitto
spec:
  ports:
  - port: 1883
    name: mqtt
  clusterIP: None
  selector:
    app: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto-svc
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
---
#apiVersion: v1
#kind: Service
#metadata:
  #labels:
    #app: mosquitto-ext
  #name: mosquitto-ext
#spec:
  #externalIPs:
  #- 192.168.1.33
  #ports:
  #- port: 1883
    #protocol: TCP
    #targetPort: 1883
  #selector:
    #app: mosquitto-svc
  #type: LoadBalancer
#---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 1
  serviceName: mosquitto-headless-service
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      nodeSelector:
        workload_generic: "1"
      containers:
      - name: mosquitto
        env:
        - name: VAR
          value: "value"
        image: eclipse-mosquitto:1.6
        ports:
        - containerPort: 1883
          # hostPort: 1883
          protocol: TCP
        livenessProbe:
          exec:
            command: 
            - /usr/bin/mosquitto_pub 
            - -t 
            - monitor/health
            - -m 
            - kube-livenessProbe
          #tcpSocket:
            #port: 1883
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /mosquitto/data
          name: volume-mosquitto-data
        - mountPath: /mosquitto/log
          name: volume-mosquitto-log
      dnsPolicy: ClusterFirst
      volumes:
      - name: volume-mosquitto-data
        emptyDir: {}
      - name: volume-mosquitto-log
        emptyDir: {}
      # - name: volume-mosquitto-data
      #   nfs:
      #     path: /srv/kube/mosquitto/data
      #     server: mifs01
      # - name: volume-mosquitto-log
      #   nfs:
      #     path: /srv/kube/mosquitto/log
      #     server: mifs01
