apiVersion: v1
kind: Service
metadata:
  name: mosquitto-headless-service
  labels:
    app: mosquitto
spec:
  ports:
  - port: 1883
    name: mqtt
  clusterIP: None
  selector:
    app: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 1
  serviceName: mosquitto-headless-service
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        env:
        - name: VAR
          value: "value"
        image: eclipse-mosquitto:1.6
        ports:
        - containerPort: 1883
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 1883
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: 1883
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /mosquitto/data
          name: volume-mosquitto-data
        - mountPath: /mosquitto/log
          name: volume-mosquitto-log
      dnsPolicy: ClusterFirst
      volumes:
      - name: volume-mosquitto-data
        nfs:
          path: /srv/kube/mosquitto/data
          server: cindy
      - name: volume-mosquitto-log
        nfs:
          path: /srv/kube/mosquitto/log
          server: cindy
