apiVersion: v1
kind: Service
metadata:
  name: nats-streaming-headless-service
  labels:
    app: nats-streaming
spec:
  ports:
  - port: 4222
    name: nats
  clusterIP: None
  selector:
    app: nats-streaming
---
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming-master
  labels:
    app: nats-streaming-master      
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: nats
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
      statefulset.kubernetes.io/pod-name: nats-streaming-0      
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nats-streaming
  name: nats-streaming
spec:
  replicas: 1
  serviceName: nats-streaming-headless-service
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
      - name: nats-streaming
        env:
        - name: VAR
          value: "value"
        image: nats-streaming:0.16.0-linux
        args: ["--store", "FILE", "--dir", "/data", "-m", "8222"]
        ports:
        - containerPort: 4222
          protocol: TCP
        - containerPort: 8222
          protocol: TCP
        livenessProbe:
          httpGet:
            port: 8222
            path: /streaming
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8222
            path: /streaming
          failureThreshold: 10
          initialDelaySeconds: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 32Mi
        volumeMounts:
        - mountPath: /data
          name: volume-nats-streaming
      dnsPolicy: ClusterFirst
      volumes:
      - name: volume-nats-streaming
        nfs:
          path: /srv/kube/nats-streaming
          server: cindy
