# NATS streaming server for kubernetes and raspberry pi

# Latest linux version (just static linked binary with no external tools or libs)
FROM nats-streaming:linux

# TODO
#  - switch to non-root user

CMD []
